# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: SlackUnread

options:
  minimumXcodeGenVersion: 2.10.0
  bundleIdPrefix: org.woodentable
  deploymentTarget:
    macOS: 11.0.0

settings:
  CODE_SIGN_STYLE: Automatic
  CODE_SIGN_IDENTITY: '-'
  DEAD_CODE_STRIPPING: YES

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    version: 5.6.0
  SwiftyAttributes:
    url: https://github.com/eddiekaiger/SwiftyAttributes.git
    version: 5.3.0

targets:
  SlackUnread:
    type: application
    platform: macOS
    sources:
      - SlackUnread/
    settings:
      base:
        INFOPLIST_FILE: SlackUnread/Info.plist
        CODE_SIGN_ENTITLEMENTS: SlackUnread/SlackUnread.entitlements
        MARKETING_VERSION: 0.1.2
        CURRENT_PROJECT_VERSION: 5
    dependencies:
      - package: SnapKit
      - package: SwiftyAttributes
  SlackUnreadTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - SlackUnreadTests/
    settings:
      base:
        INFOPLIST_FILE: SlackUnreadTests/Info.plist
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - target: SlackUnread
