# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Description of what the lane does"
  lane :build do
    # https://docs.fastlane.tools/actions
    build_mac_app(
      project: "SlackUnread.xcodeproj",
      scheme: "SlackUnread",
      clean: true,
      configuration: "Release",
      export_method: "mac-application",
      skip_codesigning: false
    )
  end
end
