name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  test:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    runs-on: macos-13
    permissions:
      # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Check version tag
        run: |
          MARKETING_VERSION=$(yq ".targets.SlackUnread.settings.base.MARKETING_VERSION" project.yml)
          echo "Marketing version: ${MARKETING_VERSION}"
          if [[ "${{ github.ref_type }}" == "tag" && "${{ github.ref_name }}" == "v${MARKETING_VERSION}" ]]; then
            exit 0
          else
            exit 1
          fi

      - name: Generate project
        uses: xavierLowmiller/xcodegen-action@1.1.2

      - name: Build
        run: fastlane build

      - name: List build files
        run: ls -lh

      - name: zip SlackUnread.app
        run: zip -r SlackUnread.zip SlackUnread.app/

      - name: Create Release
        uses: ncipollo/release-action@v1
        # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
        with:
          artifacts: "SlackUnread.zip,SlackUnread.app.dSYM.zip"
          artifactContentType: "application/zip"
          draft: false
          generateReleaseNotes: true
